export const DEFAULT_SCENE_SAMPLE_INTERVAL_SECONDS = 1;
export const DEFAULT_SCENE_DIFF_THRESHOLD = 0.3;
export const DEFAULT_SCENE_MAX_FRAMES = 600;
export const DEFAULT_SCENE_DETECTOR_WIDTH = 160;
export const DEFAULT_SCENE_DETECTOR_HEIGHT = 90;
export const DEFAULT_VISION_ANALYSIS_MAX_FRAMES = 20;
export const DEFAULT_VISION_TRANSCRIPT_WINDOW_SECONDS = 3;
export const DEFAULT_VISION_MODEL_TEMPERATURE = 0.2;
