import type { CapabilityDefinition } from "./types";

export const AGENT_NATIVE_CAPABILITIES: CapabilityDefinition[] = [
	{
		id: "tool.transcription.generate_captions",
		name: "transcription.generate_captions",
		description: "Generate captions from timeline audio",
		source: "tool",
		sourceRef: "@/agent/tools/timeline-tools-core.ts",
		domain: "transcription",
		risk: "caution",
		parameters: [],
		preconditions: ["timeline_has_audio_or_speech"],
	},
	{
		id: "tool.timeline.remove_silence",
		name: "timeline.remove_silence",
		description: "Detect and remove silence ranges from timeline",
		source: "tool",
		sourceRef: "@/agent/tools/timeline-tools-core.ts",
		domain: "audio",
		risk: "destructive",
		parameters: [],
		preconditions: ["timeline_has_audio_or_speech"],
	},
	{
		id: "tool.timeline.update_element_transform",
		name: "timeline.update_element_transform",
		description: "Update element transform properties",
		source: "tool",
		sourceRef: "@/agent/tools/timeline-tools-core.ts",
		domain: "editing",
		risk: "caution",
		parameters: [],
		preconditions: ["timeline_element_exists"],
	},
	{
		id: "tool.timeline.position_element",
		name: "timeline.position_element",
		description: "Position element by anchor and margin",
		source: "tool",
		sourceRef: "@/agent/tools/timeline-tools-core.ts",
		domain: "editing",
		risk: "caution",
		parameters: [],
		preconditions: ["timeline_element_exists", "active_project_required"],
	},
	{
		id: "tool.timeline.update_sticker_color",
		name: "timeline.update_sticker_color",
		description: "Update sticker color",
		source: "tool",
		sourceRef: "@/agent/tools/timeline-tools-core.ts",
		domain: "editing",
		risk: "caution",
		parameters: [],
		preconditions: ["sticker_element_selected_or_provided"],
	},
	{
		id: "tool.asset.search_sticker",
		name: "asset.search_sticker",
		description: "Search sticker candidates from external provider",
		source: "tool",
		sourceRef: "@/agent/tools/asset-tools-core.ts",
		domain: "media",
		risk: "safe",
		parameters: [],
		preconditions: [],
	},
	{
		id: "tool.asset.add_sticker",
		name: "asset.add_sticker",
		description: "Add sticker element to timeline",
		source: "tool",
		sourceRef: "@/agent/tools/asset-tools-core.ts",
		domain: "media",
		risk: "caution",
		parameters: [],
		preconditions: ["active_project_required"],
	},
	{
		id: "tool.asset.search_sound_effect",
		name: "asset.search_sound_effect",
		description: "Search sound effect candidates",
		source: "tool",
		sourceRef: "@/agent/tools/asset-tools-core.ts",
		domain: "audio",
		risk: "safe",
		parameters: [],
		preconditions: [],
	},
	{
		id: "tool.asset.add_sound_effect",
		name: "asset.add_sound_effect",
		description: "Add sound effect to timeline",
		source: "tool",
		sourceRef: "@/agent/tools/asset-tools-core.ts",
		domain: "audio",
		risk: "caution",
		parameters: [],
		preconditions: ["active_project_required"],
	},
	{
		id: "tool.vision.detect_scenes",
		name: "vision.detect_scenes",
		description: "Detect scene boundaries from sampled video frames",
		source: "tool",
		sourceRef: "@/agent/tools/vision-tools-core.ts",
		domain: "vision",
		risk: "safe",
		parameters: [],
		preconditions: ["video_asset_available"],
	},
	{
		id: "tool.vision.analyze_frames",
		name: "vision.analyze_frames",
		description: "Analyze sampled frames with multimodal model",
		source: "tool",
		sourceRef: "@/agent/tools/vision-tools-core.ts",
		domain: "vision",
		risk: "safe",
		parameters: [],
		preconditions: ["video_asset_available", "provider_available"],
	},
	{
		id: "tool.vision.suggest_edits",
		name: "vision.suggest_edits",
		description: "Generate edit suggestions from scene/frame analysis",
		source: "tool",
		sourceRef: "@/agent/tools/vision-tools-core.ts",
		domain: "vision",
		risk: "safe",
		parameters: [],
		preconditions: ["analysis_context_available"],
	},
	{
		id: "tool.vision.apply_layout_suggestion",
		name: "vision.apply_layout_suggestion",
		description: "Apply vision layout suggestion to element positioning",
		source: "tool",
		sourceRef: "@/agent/tools/vision-tools-core.ts",
		domain: "vision",
		risk: "caution",
		parameters: [],
		preconditions: ["analysis_context_available", "timeline_element_exists"],
	},
	{
		id: "tool.highlight.score_highlights",
		name: "highlight.score_highlights",
		description: "Score transcript segments for highlight potential",
		source: "tool",
		sourceRef: "@/agent/tools/highlight-tools-core.ts",
		domain: "highlight",
		risk: "safe",
		parameters: [],
		preconditions: ["transcript_context_available"],
	},
	{
		id: "tool.highlight.validate_highlights_visual",
		name: "highlight.validate_highlights_visual",
		description: "Validate highlight candidates with visual scoring",
		source: "tool",
		sourceRef: "@/agent/tools/highlight-tools-core.ts",
		domain: "highlight",
		risk: "safe",
		parameters: [],
		preconditions: ["highlight_scores_cached"],
	},
	{
		id: "tool.highlight.generate_highlight_plan",
		name: "highlight.generate_highlight_plan",
		description: "Generate highlight cut plan under duration constraints",
		source: "tool",
		sourceRef: "@/agent/tools/highlight-tools-core.ts",
		domain: "highlight",
		risk: "caution",
		parameters: [],
		preconditions: ["highlight_scores_cached"],
	},
	{
		id: "tool.highlight.apply_highlight_cut",
		name: "highlight.apply_highlight_cut",
		description: "Apply highlight plan to timeline",
		source: "tool",
		sourceRef: "@/agent/tools/highlight-tools-core.ts",
		domain: "highlight",
		risk: "destructive",
		parameters: [],
		preconditions: ["highlight_plan_cached", "active_project_required"],
	},
	{
		id: "tool.filler.detect_filler_words",
		name: "filler.detect_filler_words",
		description: "Detect filler words in transcript",
		source: "tool",
		sourceRef: "@/agent/tools/filler-tools.ts",
		domain: "transcription",
		risk: "safe",
		parameters: [],
		preconditions: ["transcript_context_available"],
	},
	{
		id: "tool.filler.remove_filler_words",
		name: "filler.remove_filler_words",
		description: "Remove filler-word ranges from timeline",
		source: "tool",
		sourceRef: "@/agent/tools/filler-tools.ts",
		domain: "transcription",
		risk: "destructive",
		parameters: [],
		preconditions: ["transcript_context_available", "active_project_required"],
	},
	{
		id: "tool.transcript.suggest_transcript_cuts",
		name: "transcript.suggest_transcript_cuts",
		description: "Generate transcript deletion suggestions",
		source: "tool",
		sourceRef: "@/agent/tools/transcript-edit-tools-core.ts",
		domain: "transcription",
		risk: "caution",
		parameters: [],
		preconditions: ["transcript_context_available"],
	},
	{
		id: "tool.transcript.transcript_smart_trim",
		name: "transcript.transcript_smart_trim",
		description: "Trim transcript-driven timeline to target duration",
		source: "tool",
		sourceRef: "@/agent/tools/transcript-edit-tools-core.ts",
		domain: "transcription",
		risk: "destructive",
		parameters: [],
		preconditions: ["transcript_context_available", "active_project_required"],
	},
	{
		id: "tool.capability.list_capabilities",
		name: "capability.list_capabilities",
		description: "List normalized agent capability registry entries",
		source: "tool",
		sourceRef: "@/agent/tools/capability-tools.ts",
		domain: "agent",
		risk: "safe",
		parameters: [],
		preconditions: [],
	},
	{
		id: "tool.workflow.list_workflows",
		name: "workflow.list_workflows",
		description: "List predefined workflows",
		source: "tool",
		sourceRef: "@/agent/tools/workflow-tools.ts",
		domain: "workflow",
		risk: "safe",
		parameters: [],
		preconditions: [],
	},
	{
		id: "tool.workflow.run_workflow",
		name: "workflow.run_workflow",
		description: "Execute predefined workflow",
		source: "tool",
		sourceRef: "@/agent/tools/workflow-tools.ts",
		domain: "workflow",
		risk: "caution",
		parameters: [],
		preconditions: ["workflow_exists"],
	},
	{
		id: "tool.content.generate_edit_brief",
		name: "content.generate_edit_brief",
		description: "Generate structured editing brief from one-line prompt",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "agent",
		risk: "safe",
		parameters: [],
		preconditions: [],
	},
	{
		id: "tool.content.auto_edit_from_prompt",
		name: "content.auto_edit_from_prompt",
		description: "Run one-line auto edit pipeline from brief to draft",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "workflow",
		risk: "caution",
		parameters: [],
		preconditions: ["workflow_exists"],
	},
	{
		id: "tool.content.generate_hook_variants",
		name: "content.generate_hook_variants",
		description: "Generate multiple hook variants for opening selection",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "highlight",
		risk: "safe",
		parameters: [],
		preconditions: ["transcript_context_available"],
	},
	{
		id: "tool.content.apply_caption_preset",
		name: "content.apply_caption_preset",
		description: "Apply caption style preset to caption elements",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "transcription",
		risk: "caution",
		parameters: [],
		preconditions: ["caption_elements_available"],
	},
	{
		id: "tool.content.export_multi_ratio",
		name: "content.export_multi_ratio",
		description: "Export project in multiple aspect ratios",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "project",
		risk: "caution",
		parameters: [],
		preconditions: ["active_project_required"],
	},
	{
		id: "tool.content.evaluate_timeline_quality",
		name: "content.evaluate_timeline_quality",
		description: "Evaluate timeline quality and output structured report",
		source: "tool",
		sourceRef: "@/agent/tools/content-tools-core.ts",
		domain: "workflow",
		risk: "safe",
		parameters: [],
		preconditions: ["timeline_loaded"],
	},
];

export const TOOL_CAPABILITY_BINDINGS: Record<string, string[]> = {
	split_at_playhead: ["action.split"],
	split_at_time: [
		"manager.timeline.splitElements",
		"manager.playback.getIsScrubbing",
	],
	delete_selected: ["action.delete-selected"],
	delete_element_by_id: ["manager.timeline.deleteElements"],
	split_left: ["action.split-left"],
	split_right: ["action.split-right"],
	duplicate_selected: ["action.duplicate-selected"],
	select_all: ["action.select-all"],
	select_element: ["manager.selection.setSelectedElements"],
	clear_selection: ["manager.selection.clearSelection"],
	add_track: ["manager.timeline.addTrack"],
	remove_track: ["manager.timeline.removeTrack"],
	toggle_track_mute: ["manager.timeline.toggleTrackMute"],
	toggle_track_visibility: ["manager.timeline.toggleTrackVisibility"],
	generate_captions: ["tool.transcription.generate_captions"],
	update_text_style: ["manager.timeline.updateElements"],
	move_element: ["manager.timeline.moveElement"],
	move_elements: ["manager.timeline.updateElementStartTime"],
	trim_element: ["manager.timeline.updateElementTrim"],
	resize_element: ["manager.timeline.updateElementDuration"],
	update_element_transform: ["manager.timeline.updateElements"],
	position_element: ["manager.timeline.updateElements"],
	update_sticker_color: ["manager.timeline.updateElements"],
	remove_silence: ["tool.timeline.remove_silence"],
	insert_text: ["manager.timeline.insertElement"],
	toggle_play: ["action.toggle-play"],
	seek_forward: ["action.seek-forward"],
	seek_backward: ["action.seek-backward"],
	jump_forward: ["action.jump-forward"],
	jump_backward: ["action.jump-backward"],
	seek_to_time: ["manager.playback.seek", "manager.playback.getIsScrubbing"],
	go_to_start: ["action.goto-start"],
	go_to_end: ["action.goto-end"],
	set_volume: ["manager.playback.setVolume"],
	toggle_playback_mute: ["manager.playback.toggleMute"],
	stop_playback: ["action.stop-playback"],
	undo: ["action.undo"],
	redo: ["action.redo"],
	get_timeline_info: ["manager.timeline.getTracks"],
	get_total_duration: ["manager.timeline.getTotalDuration"],
	get_current_time: ["manager.playback.getCurrentTime"],
	get_selected_elements: ["manager.selection.getSelectedElements"],
	get_element_details: ["manager.timeline.getElementsWithTracks"],
	get_elements_in_range: ["manager.timeline.getTracks"],
	get_track_details: ["manager.timeline.getTrackById"],
	get_timeline_summary: ["manager.timeline.getTracks"],
	copy_selected: ["action.copy-selected"],
	paste_copied: ["action.paste-copied"],
	paste_at_time: ["action.paste-at-time"],
	toggle_mute_selected: ["action.toggle-elements-muted-selected"],
	toggle_visibility_selected: ["action.toggle-elements-visibility-selected"],
	toggle_snapping: ["action.toggle-snapping"],
	toggle_bookmark: ["action.toggle-bookmark"],
	toggle_bookmark_at_time: ["manager.scenes.toggleBookmark"],
	get_bookmarks: ["manager.scenes.getActiveScene"],
	create_scene: ["manager.scenes.createScene"],
	switch_scene: ["manager.scenes.switchToScene"],
	list_scenes: ["manager.scenes.getScenes"],
	rename_scene: ["manager.scenes.renameScene"],
	delete_scene: ["manager.scenes.deleteScene"],
	frame_step_forward: ["action.frame-step-forward"],
	frame_step_backward: ["action.frame-step-backward"],
	list_assets: ["manager.media.getAssets"],
	add_asset_to_timeline: ["manager.timeline.insertElement"],
	search_sticker: ["tool.asset.search_sticker"],
	add_sticker: ["tool.asset.add_sticker"],
	search_sound_effect: ["tool.asset.search_sound_effect"],
	add_sound_effect: ["tool.asset.add_sound_effect"],
	add_media_asset: ["manager.media.addMediaAsset"],
	remove_asset: ["manager.media.removeMediaAsset"],
	export_video: ["manager.project.export"],
	update_project_settings: ["manager.project.updateSettings"],
	get_project_info: ["manager.project.getActiveOrNull"],
	save_project: ["manager.project.saveCurrentProject"],
	detect_scenes: ["tool.vision.detect_scenes"],
	analyze_frames: ["tool.vision.analyze_frames"],
	apply_layout_suggestion: [
		"tool.vision.apply_layout_suggestion",
		"tool.timeline.position_element",
	],
	suggest_edits: ["tool.vision.suggest_edits"],
	score_highlights: ["tool.highlight.score_highlights"],
	validate_highlights_visual: ["tool.highlight.validate_highlights_visual"],
	generate_highlight_plan: ["tool.highlight.generate_highlight_plan"],
	apply_highlight_cut: ["tool.highlight.apply_highlight_cut"],
	detect_filler_words: ["tool.filler.detect_filler_words"],
	remove_filler_words: ["tool.filler.remove_filler_words"],
	suggest_transcript_cuts: ["tool.transcript.suggest_transcript_cuts"],
	transcript_smart_trim: ["tool.transcript.transcript_smart_trim"],
	list_capabilities: ["tool.capability.list_capabilities"],
	list_workflows: ["tool.workflow.list_workflows"],
	run_workflow: ["tool.workflow.run_workflow"],
	generate_edit_brief: ["tool.content.generate_edit_brief"],
	auto_edit_from_prompt: ["tool.content.auto_edit_from_prompt"],
	generate_hook_variants: ["tool.content.generate_hook_variants"],
	apply_caption_preset: ["tool.content.apply_caption_preset"],
	export_multi_ratio: ["tool.content.export_multi_ratio"],
	evaluate_timeline_quality: ["tool.content.evaluate_timeline_quality"],
};

export function getToolCapabilityIds(toolName: string): string[] {
	return TOOL_CAPABILITY_BINDINGS[toolName] ?? [];
}
